package cmd

import (
	"os"
	"text/template"

	"github.com/mmahyar639-del/bughunter-toolkit/internal/modules/api_fuzzer"
	"github.com/mmahyar639-del/bughunter-toolkit/internal/modules/js_analyzer"
	"github.com/mmahyar639-del/bughunter-toolkit/internal/modules/takeover"
)

type HTMLReportData struct {
	Target      string
	Timestamp   string
	JSSecrets   []js_analyzer.Finding
	FuzzResults []api_fuzzer.FuzzResult
	Takeovers   []takeover.ResolveResult
}

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BugHunter Report - {{.Target}}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f4f7f6; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; margin-top: 30px; }
        .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; color: #fff; }
        .badge-secret { background: #e74c3c; }
        .badge-endpoint { background: #3498db; }
        .badge-fuzz { background: #f39c12; }
        .badge-takeover { background: #8e44ad; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; word-break: break-all; }
        th { background: #f8f9fa; color: #2c3e50; }
        .code { background: #2c3e50; color: #2ecc71; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 13px; }
        .footer { margin-top: 40px; text-align: center; color: #7f8c8d; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ BugHunter Toolkit Report</h1>
        <p><strong>Target:</strong> {{.Target}} | <strong>Timestamp:</strong> {{.Timestamp}}</p>

        <h2>🔍 JS Analyzer Findings ({{len .JSSecrets}})</h2>
        {{if .JSSecrets}}
        <table>
            <tr><th>Type</th><th>Value</th></tr>
            {{range .JSSecrets}}
            <tr>
                <td><span class="badge {{if contains .Type "SECRET"}}badge-secret{{else}}badge-endpoint{{end}}">{{.Type}}</span></td>
                <td><span class="code">{{.Value}}</span></td>
            </tr>
            {{end}}
        </table>
        {{else}}
        <p>No secrets or endpoints found.</p>
        {{end}}

        <h2>🎯 Smart Fuzzer Anomalies ({{len .FuzzResults}})</h2>
        {{if .FuzzResults}}
        <table>
            <tr><th>URL</th><th>Parameter</th><th>Payload</th><th>Reason</th></tr>
            {{range .FuzzResults}}
            <tr>
                <td><span class="code">{{.URL}}</span></td>
                <td>{{.ParamName}}</td>
                <td><span class="code">{{.Payload}}</span></td>
                <td><span class="badge badge-fuzz">{{.Reason}}</span></td>
            </tr>
            {{end}}
        </table>
        {{else}}
        <p>No anomalies detected.</p>
        {{end}}

        <h2>🌐 Subdomain Takeovers ({{len .Takeovers}})</h2>
        {{if .Takeovers}}
        <table>
            <tr><th>Subdomain</th><th>Service</th><th>CNAME</th></tr>
            {{range .Takeovers}}
            <tr>
                <td><strong>{{.Subdomain}}</strong></td>
                <td><span class="badge badge-takeover">{{.Service}}</span></td>
                <td>{{range .CNAMEs}}<span class="code">{{.}}</span> {{end}}</td>
            </tr>
            {{end}}
        </table>
        {{else}}
        <p>No takeovers detected.</p>
        {{end}}

        <div class="footer">
            Generated by BugHunter Toolkit v1.0.0 | Created by @mmahyar639
        </div>
    </div>
</body>
</html>`

// GenerateHTMLReport گزارش نهایی را به صورت یک فایل HTML زیبا ذخیره می‌کند
func GenerateHTMLReport(data HTMLReportData, outputPath string) error {
	funcMap := template.FuncMap{
		"contains": func(s, substr string) bool {
			for i := 0; i <= len(s)-len(substr); i++ {
				if s[i:i+len(substr)] == substr {
					return true
				}
			}
			return false
		},
	}
	
	tmpl, err := template.New("report").Funcs(funcMap).Parse(htmlTemplate)
	if err != nil {
		return err
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}